create database catalogo_pokemons;

drop table if exists usuarios;

create table usuarios (
    id serial primary key,
    nome text not null,
    email text not null unique,
    senha text not null
);

drop table if exists pokemons;

create table pokemons(
    id serial primary key,
    usuario_id int not null,
    nome text not null,
    habilidades text not null,
    imagem text,
    apelido text
);